
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA ENTERO EQUALS FIN IDENTIFIER INICIO LBRACE LPAREN PROCESO RBRACE RPAREN SEMICOLON SI VALOR VARIABLE VERprogram : inicio cadena entero proceso si fininicio : INICIO SEMICOLONcadena : CADENA VARIABLE EQUALS VALOR SEMICOLONentero : ENTERO VARIABLE EQUALS VALOR SEMICOLONstatement_block : LBRACE statement si2 RBRACEstatement_block2 : LBRACE statement RBRACEproceso : PROCESO SEMICOLONsi : SI LPAREN VALOR EQUALS EQUALS VALOR RPAREN statement_blockstatement : VER VALOR SEMICOLONsi2 : SI LPAREN VARIABLE EQUALS EQUALS VALOR RPAREN statement_block2fin : FIN SEMICOLON'
    
_lr_action_items = {'INICIO':([0,],[3,]),'$end':([1,19,24,],[0,-1,-11,]),'CADENA':([2,6,],[5,-2,]),'SEMICOLON':([3,11,18,20,22,37,],[6,16,23,24,26,40,]),'ENTERO':([4,23,],[8,-3,]),'VARIABLE':([5,8,39,],[9,12,41,]),'PROCESO':([7,26,],[11,-4,]),'EQUALS':([9,12,25,27,41,42,],[13,17,27,28,42,43,]),'SI':([10,16,33,40,],[15,-7,36,-9,]),'VALOR':([13,17,21,28,34,43,],[18,22,25,29,37,44,]),'FIN':([14,31,38,],[20,-8,-5,]),'LPAREN':([15,36,],[21,39,]),'RPAREN':([29,44,],[30,45,]),'LBRACE':([30,45,],[32,47,]),'VER':([32,47,],[34,34,]),'RBRACE':([35,40,46,48,49,],[38,-9,-10,49,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'inicio':([0,],[2,]),'cadena':([2,],[4,]),'entero':([4,],[7,]),'proceso':([7,],[10,]),'si':([10,],[14,]),'fin':([14,],[19,]),'statement_block':([30,],[31,]),'statement':([32,47,],[33,48,]),'si2':([33,],[35,]),'statement_block2':([45,],[46,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> inicio cadena entero proceso si fin','program',6,'p_program','Analizador.py',85),
  ('inicio -> INICIO SEMICOLON','inicio',2,'p_inicio','Analizador.py',89),
  ('cadena -> CADENA VARIABLE EQUALS VALOR SEMICOLON','cadena',5,'p_declaracion','Analizador.py',93),
  ('entero -> ENTERO VARIABLE EQUALS VALOR SEMICOLON','entero',5,'p_eclaracion2','Analizador.py',99),
  ('statement_block -> LBRACE statement si2 RBRACE','statement_block',4,'p_statement_block','Analizador.py',105),
  ('statement_block2 -> LBRACE statement RBRACE','statement_block2',3,'p_statement_block2','Analizador.py',109),
  ('proceso -> PROCESO SEMICOLON','proceso',2,'p_proceso','Analizador.py',113),
  ('si -> SI LPAREN VALOR EQUALS EQUALS VALOR RPAREN statement_block','si',8,'p_si','Analizador.py',117),
  ('statement -> VER VALOR SEMICOLON','statement',3,'p_statement','Analizador.py',121),
  ('si2 -> SI LPAREN VARIABLE EQUALS EQUALS VALOR RPAREN statement_block2','si2',8,'p_si2','Analizador.py',125),
  ('fin -> FIN SEMICOLON','fin',2,'p_fin','Analizador.py',146),
]
