
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COUT DOTDOT EQUALS HASH IDENTIFIER INCLUDE INT IOSTREAM LBRACE LPAREN MAIN MAYOR MENOR RBRACE RETURN RPAREN SEMICOLON STD VALOR VARIABLEprogram : inicio variable funtionvariable : INT VARIABLE EQUALS VALOR SEMICOLONinicio : HASH INCLUDE MENOR IOSTREAM MAYORfuntion : INT MAIN LPAREN RPAREN statement_blockstatement_block : LBRACE statement return RBRACEreturn : RETURN VALOR SEMICOLONstatement : STD DOTDOT DOTDOT COUT MENOR MENOR VARIABLE SEMICOLON'
    
_lr_action_items = {'HASH':([0,],[3,]),'$end':([1,7,19,26,],[0,-1,-4,-5,]),'INT':([2,4,16,18,],[5,8,-3,-2,]),'INCLUDE':([3,],[6,]),'VARIABLE':([5,32,],[9,33,]),'MENOR':([6,30,31,],[10,31,32,]),'MAIN':([8,],[11,]),'EQUALS':([9,],[12,]),'IOSTREAM':([10,],[13,]),'LPAREN':([11,],[14,]),'VALOR':([12,24,],[15,27,]),'MAYOR':([13,],[16,]),'RPAREN':([14,],[17,]),'SEMICOLON':([15,27,33,],[18,29,34,]),'LBRACE':([17,],[20,]),'STD':([20,],[22,]),'RETURN':([21,34,],[24,-7,]),'DOTDOT':([22,25,],[25,28,]),'RBRACE':([23,29,],[26,-6,]),'COUT':([28,],[30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'inicio':([0,],[2,]),'variable':([2,],[4,]),'funtion':([4,],[7,]),'statement_block':([17,],[19,]),'statement':([20,],[21,]),'return':([21,],[23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> inicio variable funtion','program',3,'p_program','Analizador.py',123),
  ('variable -> INT VARIABLE EQUALS VALOR SEMICOLON','variable',5,'p_variable','Analizador.py',127),
  ('inicio -> HASH INCLUDE MENOR IOSTREAM MAYOR','inicio',5,'p_inicio','Analizador.py',132),
  ('funtion -> INT MAIN LPAREN RPAREN statement_block','funtion',5,'p_declaracion','Analizador.py',136),
  ('statement_block -> LBRACE statement return RBRACE','statement_block',4,'p_statement_block','Analizador.py',140),
  ('return -> RETURN VALOR SEMICOLON','return',3,'p_proceso','Analizador.py',144),
  ('statement -> STD DOTDOT DOTDOT COUT MENOR MENOR VARIABLE SEMICOLON','statement',8,'p_statement','Analizador.py',148),
]
